// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtqzxtqmqxqorpamsllm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cXp4dHFtcXhxb3JwYW1zbGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTc5MjksImV4cCI6MjA2NjY5MzkyOX0.2DIDQWlNvqEzcOoxnD9LeneFJ83P7nM75k9OoScWe3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);